### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ajo01** [ajo01/cloud-resume-challenge#1]
- [x] Use Terraform
- [x] Make AWS diagram 
- [x] Update Github readme & link guide
- [x] Create Blog post how to guide
